Copter: use udp transport in launch
ArduPilot/ardupilot_gz pull request #16
Opened 2023-05-09 09:31 UTC by srmainwaring

Update the launch script for the iris quadcopter example to use UDP transport.

- Use UDP transport as default (instead of serial with virtual ports).
- Update config file (remove leading `/` so ROS topics are not all in global namespace).
- Update dependencies to use ArduPilot versions of repos where available.

## Dependencies

- https://github.com/ArduPilot/ardupilot/pull/23703

2023-05-11 15:02 UTC, Ryanf55 requested changes

2023-05-11 15:02 UTC, Ryanf55 commented on ros2_gz_macos.repos
> +    url: https://github.com/eProsima/Micro-XRCE-DDS-Gen.git
Can we use ardupilot's fork?

2023-05-11 15:02 UTC, Ryanf55 commented on ros2_gz_macos.repos
> +    url: https://github.com/micro-ROS/micro_ros_msgs.git
Should Ardupilot fork this?

2023-05-11 15:02 UTC, Ryanf55 commented on ros2_gz_macos.repos
> +    url: https://github.com/srmainwaring/micro-ROS-Agent.git
If your changes are pushed to the Ardupilot version, should we use Ardupilot's fork?

2023-05-11 15:33 UTC, srmainwaring commented on ros2_gz_macos.repos
> +    url: https://github.com/micro-ROS/micro_ros_msgs.git
No. There's a deb on Ubuntu. On macOS everything must be built from source and this is not part of the humble-desktop.

2023-05-11 15:35 UTC, srmainwaring commented on ros2_gz_macos.repos
> +    url: https://github.com/srmainwaring/micro-ROS-Agent.git
ArduPilot doesn't have a fork of the agent, just the client. I'm hoping to close the last remaining macOS specific difference which will then allow us to use the same version for Ubuntu and macOS.

2023-05-11 15:38 UTC, srmainwaring commented on ros2_gz_macos.repos
> +    url: https://github.com/eProsima/Micro-XRCE-DDS-Gen.git
ArduPilot doesn't have a fork of the generator, just CDR and the client. I could remove this as I just included it for convenience on macOS, it's not actually a direct run-time dependency of any of the packages - just a build tool dependency.

2023-05-12 00:27 UTC, Ryanf55 commented on ros2_gz_macos.repos
> +    url: https://github.com/eProsima/Micro-XRCE-DDS-Gen.git
https://github.com/ArduPilot/Micro-XRCE-DDS-Gen

2023-05-12 08:18 UTC, srmainwaring commented on ros2_gz_macos.repos
> +    url: https://github.com/eProsima/Micro-XRCE-DDS-Gen.git
Ahh! I was looking in modules. Ok - I'll nix the entry from the repos file as it's not part of the build.

Updated in bc8af07.

2023-05-13 10:29 UTC, srmainwaring commented
@Ryanf55 - github seems to have got stuck on this PR (can't get it to acknowledge I've made changes). Should be resolved now and ready for approval.

2023-05-13 14:30 UTC, Ryanf55 approved these changes

2023-05-13 21:29 UTC, merged