Rover: add lidar to rover example
ArduPilot/ardupilot_gz pull request #34
Opened 2023-10-07 14:55 UTC by srmainwaring

This is a follow up to https://github.com/ArduPilot/ardupilot_gz/pull/33 that adds a lidar to the rover model. It enables the rover model to be used with the cartographer and navigation launch configurations developed by @pedro-fuoco as part of his 2023 GSoC project. 

### Dependencies

- https://github.com/ArduPilot/ardupilot_gz/pull/33
- https://github.com/ArduPilot/SITL_Models/pull/101
- https://github.com/ArduPilot/ardupilot/pull/25204

For testing and further details see the descriptions in the above PRs.

### Tasks

- [ ] rebase once https://github.com/ArduPilot/ardupilot_gz/pull/33 is merged

2023-10-25 02:23 UTC, Ryanf55 requested changes
Works well, only thing was for building, do this instead of what you said:
```
colcon build --packages-up-to ardupilot_gz_bringup
```

Do you intend to add the models repo to here: `https://raw.githubusercontent.com/ArduPilot/ardupilot_gz/main/ros2_gz.repos`?

When testing, looks a package wasn't build that needed to be. `ros_gz_bridge` missing dependency. 

```
ryan@B650-970:~/Dev/ros2_ws$ ros2 launch ardupilot_gz_bringup wildthumper_playpen.launch.py rviz:=true use_gz_tf:=true
[INFO] [launch]: All log files can be found below /home/ryan/.ros/log/2023-10-24-20-22-46-006796-B650-970-94165
[INFO] [launch]: Default logging verbosity is set to INFO
namespace:        
transport:        udp4
middleware:       dds
verbose:          4
discovery:        7400
port:             2019
refs:             /home/ryan/Dev/ros2_ws/install/ardupilot_sitl/share/ardupilot_sitl/config/dds_xrce_profile.xml
command:          ardurover
model:            json
speedup:          1
slave:            0
sim_address:      127.0.0.1
instance:         0
defaults:         /home/ryan/Dev/ros2_ws/install/ardupilot_sitl/share/ardupilot_sitl/config/default_params/rover-skid.parm,/home/ryan/Dev/ros2_ws/install/ardupilot_sitl/share/ardupilot_sitl/config/default_params/dds_udp.parm
synthetic_clock:  True
command:          mavproxy.py
master:           tcp:127.0.0.1:5760
sitl:             127.0.0.1:5501
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'ros_gz_bridge' not found, searching: ['/home/ryan/Dev/ros2_ws/install/ardupilot_gz_bringup', '/home/ryan/Dev/ros2_ws/install/ros_gz_sim', '/home/ryan/Dev/ros2_ws/install/ardupilot_sitl', '/home/ryan/Dev/ros2_ws/install/micro_ros_agent', '/home/ryan/Dev/ros2_ws/install/ardupilot_sitl_models', '/home/ryan/Dev/ros2_ws/install/ardupilot_msgs', '/home/ryan/Dev/ros2_ws/install/ardupilot_gz_gazebo', '/home/ryan/Dev/ros2_ws/install/ardupilot_gz_description', '/opt/ros/humble']"
````

2023-10-25 09:23 UTC, srmainwaring commented
> Here's a patch: [srmainwaring#1](https://github.com/srmainwaring/ardupilot_gz/pull/1)

Merged and updated in PR.

2023-10-25 11:00 UTC, srmainwaring commented
> Do you intend to add the models repo to here: `https://raw.githubusercontent.com/ArduPilot/ardupilot_gz/main/ros2_gz.repos`?

https://github.com/ArduPilot/ardupilot_gz/pull/34/commits/0a570cd1e9244b33bbf5a3bc6795ee8b589edcb0

2023-10-26 17:52 UTC, Ryanf55 commented
With latest changes: 
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'topic_tools' not found, searching: ['/home/ryan/Dev/ros2_ws/install_humble/ardupilot_gz_bringup', '/home/ryan/Dev/ros2_ws/install_humble/ros_gz_sim', '/home/ryan/Dev/ros2_ws/install_humble/ros_gz_bridge', '/home/ryan/Dev/ros2_ws/install_humble/ros_gz_interfaces', '/home/ryan/Dev/ros2_ws/install_humble/ardupilot_sitl', '/home/ryan/Dev/ros2_ws/install_humble/micro_ros_agent', '/home/ryan/Dev/ros2_ws/install_humble/ardupilot_sitl_models', '/home/ryan/Dev/ros2_ws/install_humble/ardupilot_gz_gazebo', '/home/ryan/Dev/ros2_ws/install_humble/ardupilot_gz_description', '/home/ryan/Dev/ros2_ws/install_humble/ardupilot_gazebo', '/home/ryan/Dev/ros2_ws/install/ardupilot_sitl_models', '/home/ryan/Dev/ros2_ws/install/ardupilot_gazebo', '/home/ryan/Dev/ros2_ws/install/ardupilot_gz_bringup', '/home/ryan/Dev/ros2_ws/install/ros_gz_sim', '/home/ryan/Dev/ros2_ws/install/ardupilot_sitl', '/home/ryan/Dev/ros2_ws/install/micro_ros_agent', '/home/ryan/Dev/ros2_ws/install/ardupilot_gz_gazebo', '/home/ryan/Dev/ros2_ws/install/ardupilot_gz_description', '/opt/ros/humble']"
```
Perhaps add this to the workspace or package.xml if binaries are available?
https://github.com/ros-tooling/topic_tools

2023-10-26 17:55 UTC, srmainwaring commented
Ah, thought I'd added `topic_tools` to the `package.xml` already. Will update.

2023-10-26 18:27 UTC, Ryanf55 commented
> Ah, thought I'd added `topic_tools` to the `package.xml` already. Will update.

Seems like it's an issue for `iris_maze.launch.py` also.

2023-10-26 21:50 UTC, srmainwaring commented
> Seems like it's an issue for iris_maze.launch.py also; it was missed earlier.

No, wasn't missed. A dependency on `topic_tools ` is in `main` as an `<exec_depend>`:
 
https://github.com/ArduPilot/ardupilot_gz/blob/6057dfa2462c7dc6c98e033e7040872c87b48b54/ardupilot_gz_bringup/package.xml#L9-L22

2023-10-26 21:56 UTC, Ryanf55 commented
> > Seems like it's an issue for iris_maze.launch.py also; it was missed earlier.
> 
> No, wasn't missed. A dependency on `topic_tools ` is in `main` as an `<exec_depend>`:
> 
> https://github.com/ArduPilot/ardupilot_gz/blob/6057dfa2462c7dc6c98e033e7040872c87b48b54/ardupilot_gz_bringup/package.xml#L9-L22

Ah my bad, I missed the rosdep call. Alright, after re-running that, robot_state_publisher is crashing. 
```
ryan@B650-970:~/Dev/ros2_ws$ ros2 launch ardupilot_gz_bringup iris_runway.launch.py rviz:=true use_gz_tf:=true
[INFO] [launch]: All log files can be found below /home/ryan/.ros/log/2023-10-26-15-54-35-059657-B650-970-144838
[INFO] [launch]: Default logging verbosity is set to INFO
namespace:        
transport:        udp4
middleware:       dds
verbose:          4
discovery:        7400
port:             2019
refs:             /home/ryan/Dev/ros2_ws/install_humble/ardupilot_sitl/share/ardupilot_sitl/config/dds_xrce_profile.xml
command:          arducopter
model:            json
speedup:          1
slave:            0
sim_address:      127.0.0.1
instance:         0
defaults:         /home/ryan/Dev/ros2_ws/install_humble/ardupilot_gazebo/share/ardupilot_gazebo/config/gazebo-iris-gimbal.parm,/home/ryan/Dev/ros2_ws/install_humble/ardupilot_sitl/share/ardupilot_sitl/config/default_params/dds_udp.parm
synthetic_clock:  True
command:          mavproxy.py
master:           tcp:127.0.0.1:5760
sitl:             127.0.0.1:5501
[INFO] [ruby $(which gz) sim-1]: process started with pid [144839]
[INFO] [ruby $(which gz) sim-2]: process started with pid [144841]
[INFO] [micro_ros_agent-3]: process started with pid [144843]
[INFO] [dds_udp.parm --synthetic-clock -4]: process started with pid [144845]
[INFO] [mavproxy.py --out 127.0.0.1:14550 --out 127.0.0.1:14551 --master tcp:127.0.0.1:5760 --sitl 127.0.0.1:5501 --non-interactive -5]: process started with pid [144848]
[INFO] [robot_state_publisher-6]: process started with pid [144851]
[INFO] [parameter_bridge-7]: process started with pid [144856]
[INFO] [rviz2-8]: process started with pid [144858]
[dds_udp.parm --synthetic-clock -4] Setting SIM_SPEEDUP=1.000000
[dds_udp.parm --synthetic-clock -4] Starting SITL: JSON
[dds_udp.parm --synthetic-clock -4] JSON control interface set to 127.0.0.1:9002
[dds_udp.parm --synthetic-clock -4] Starting sketch 'ArduCopter'
[dds_udp.parm --synthetic-clock -4] Starting SITL input
[dds_udp.parm --synthetic-clock -4] Using Irlock at port : 9005
[dds_udp.parm --synthetic-clock -4] Waiting for connection ....
[INFO] [relay-9]: process started with pid [144861]
[dds_udp.parm --synthetic-clock -4] bind port 5760 for 0
[dds_udp.parm --synthetic-clock -4] Serial port 0 on TCP port 5760
[micro_ros_agent-3] [1698357275.179578] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 2019
[micro_ros_agent-3] [1698357275.180044] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4
[robot_state_publisher-6] Error:   Could not find the 'robot' element in the xml file
[robot_state_publisher-6]          at line 109 in ./urdf_parser/src/model.cpp
[robot_state_publisher-6] Failed to parse robot description using: urdf_xml_parser/URDFXMLParser
[robot_state_publisher-6] terminate called after throwing an instance of 'std::runtime_error'
[robot_state_publisher-6]   what():  Unable to initialize urdf::model from robot description

```

This is with the command in the README.

2023-10-26 22:19 UTC, srmainwaring commented
Now that looks like a missing exec dependency on `sdformat_urdf`.

2023-10-27 00:10 UTC, Ryanf55 requested changes
The code is working, the lidar is added and detecting in rviz. I could spin it around with `rc 1 1450` and see the lidar continues to report in the correct frame (static with respect to the world). 

![image](https://github.com/ArduPilot/ardupilot_gz/assets/25047695/5b9f5694-d19d-4fdb-afd1-d5f2ac7b6f9f)

Just a minor change needed on branch names.

2023-10-27 00:10 UTC, Ryanf55 commented on ros2_gz.repos
> +    version: main
Do we need to switch SITL_Models to have default `main` instead of `master`?

```
ryan@B650-970:~/Dev/ros2_ws/src/SITL_Models$ git branch
* master
ryan@B650-970:~/Dev/ros2_ws/src/SITL_Models$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
ryan@B650-970:~/Dev/ros2_ws/src/SITL_Models$ git remote -v
origin	https://github.com/ArduPilot/SITL_Models.git (fetch)
origin	https://github.com/ArduPilot/SITL_Models.git (push)
```

2023-10-27 00:10 UTC, Ryanf55 commented on ros2_gz_macos.repos
> +    version: main
Same as the other comment

2023-10-27 00:29 UTC, Ryanf55 commented on ros2_gz.repos
> +    version: main
I added `main` as a branch, same as `master`. Merging as is.

2023-10-27 00:29 UTC, Ryanf55 commented on ros2_gz_macos.repos
> +    version: main
ditto

2023-10-27 00:29 UTC, Ryanf55 approved these changes

2023-10-27 00:29 UTC, merged